name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # ou 'master' se seu branch principal for 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .  # Esse é o diretório raiz onde o index.html está localizado

